#MySql Database Information
#jdbc.driver=com.mysql.cj.jdbc.Driver
#jdbc.url=jdbc:mysql:///SPRING_FACTORY
#jdbc.username=root
#jdbc.password=Raja@123
#jdbc.minimumIdle=10
#jdbc.maximumPoolSize=1000
#jdbc.idleTimeout=30000



#Oracle Database Information
jdbc.driver=oracle.jdbc.OracleDriver
jdbc.url=jdbc:oracle:thin:@localhost:1521:xe
jdbc.username=system
jdbc.password=root
jdbc.minimumIdle=10
jdbc.maximumPoolSize=1000
jdbc.idleTimeout=30000